import FormCreateFactory from "./frame/index";
import Creator, { creatorFactory } from "./factory/creator";
import Manager from "./factory/manager";
import { copyRule, copyRules, mergeRule, invoke } from "./frame/util";
import {
  debounce,
  toArray,
  toString,
  toLine,
  toDate,
  deepExtend,
  deepExtendArgs,
  deepCopy,
  extend,
  copy,
  parseJson,
  toJson,
  parseFn,
  $set,
  $del,
  is,
  hasProperty,
  uniqueId,
  uniqueId8,
  getSlot,
  deepSet,
  mergeProps,
  normalMerge,
  functionalMerge,
  toArrayMerge,
  Mitt,
  toCase,
  upper,
  lower,
  logError,
  format,
  tip,
  err,
  createFormDataQuery,
  mergeFormDataRecord,
  normalizeQueryField,
  resolveFormDataValue,
  resolveQueryFilter,
  stringifyFormDataValue,
} from "./utils";
import { fragment, FcSubForm } from "./components";
import fetch from "./frame/fetch";

export {
  FormCreateFactory,
  creatorFactory,
  Creator,
  Manager,
  copyRule,
  copyRules,
  mergeRule,
  invoke,
  fragment,
  FcSubForm,
  fetch,
  debounce,
  toArray,
  toString,
  toLine,
  toDate,
  deepExtend,
  deepExtendArgs,
  deepCopy,
  extend,
  copy,
  parseJson,
  toJson,
  parseFn,
  $set,
  $del,
  is,
  hasProperty,
  uniqueId,
  uniqueId8,
  getSlot,
  deepSet,
  mergeProps,
  normalMerge,
  functionalMerge,
  toArrayMerge,
  Mitt,
  toCase,
  upper,
  lower,
  logError,
  format,
  tip,
  err,
  createFormDataQuery,
  mergeFormDataRecord,
  normalizeQueryField,
  resolveFormDataValue,
  resolveQueryFilter,
  stringifyFormDataValue,
};
