// const PRE = "el";
// export default {
//   button: "el-button",
//   icon: "el-icon",
//   slider: "el-slider",
//   rate: "el-rate",
//   upload: "fc-upload",
//   cascader: "el-cascader",
//   popover: "el-popover",
//   tooltip: "el-tooltip",
//   colorPicker: "el-colorPicker",
//   timePicker: "el-time-picker",
//   timeSelect: "el-time-select",
//   datePicker: "el-date-picker",
//   switch: "el-switch",
//   select: "fc-select",
//   checkbox: "fc-checkbox",
//   radio: "fc-radio",
//   inputNumber: "el-input-number",
//   number: "el-input-number",
//   input: "el-input",
//   formItem: "el-form-item",
//   form: "el-form",
//   frame: "fc-frame",
//   col: "el-col",
//   row: "el-row",
//   tree: "fc-tree",
//   autoComplete: "el-autocomplete",
//   auto: "el-autocomplete",
//   group: "fc-group",
//   array: "fc-group",
//   object: "fc-sub-form",
//   subForm: "fc-sub-form",
// };

export default {
  button: "el-button",
  icon: "el-icon",
  slider: "el-slider",
  rate: "el-rate",
  fileUpload: "fc-upload",
  imageUpload: "fc-upload",
  cascader: "el-cascader",
  popover: "el-popover",
  tooltip: "el-tooltip",
  colorPicker: "el-colorPicker",
  timePicker: "el-time-picker",
  timeSelect: "el-time-select",
  timestamp: "el-date-picker",
  switch: "el-switch",
  select: "fc-select",
  select2: "fc-select",
  checkbox: "fc-checkbox",
  radio: "fc-radio",
  number: "el-input-number",
  inputNumber: "el-input-number",
  input: "el-input",
  textarea: "el-input",
  formItem: "el-form-item",
  form: "el-form",
  frame: "fc-frame",
  col: "el-col",
  row: "el-row",
  tree: "fc-tree",
  autoComplete: "el-autocomplete",
  auto: "el-autocomplete",
  group: "fc-group",
  array: "fc-group",
  object: "fc-sub-form",
  subForm: "fc-sub-form",
};
