const PRE = "van";
export default {
  button: PRE + "-button",
  icon: PRE + "-icon",
  slider: PRE + "-slider",
  stepper: PRE + "-stepper",
  rate: PRE + "-rate",
  fileUpload: "fc-uploader",
  imageUpload: "fc-uploader",
  cell: PRE + "-cell",
  timePicker: "fc-time-picker",
  timestamp: "fc-date-picker",
  colorPicker: "fc-color-picker",
  switch: PRE + "-switch",
  select: "fc-select",
  select2: "fc-select",
  cascader: "fc-cascader",
  calendar: "fc-calendar",
  checkbox: "fc-checkbox",
  radio: "fc-radio",
  number: "fc-number",
  inputNumber: "fc-number",
  input: PRE + "-field",
  textarea: PRE + "-field",
  field: PRE + "-field",
  formItem: PRE + "-field",
  form: PRE + "-form",
  col: PRE + "-col",
  row: PRE + "-row",
  group: "fc-group",
  array: "fc-group",
  object: "fc-sub-form",
  subForm: "fc-sub-form",
  serialno: "fc-serialno",
  department1: "fc-department-select",
  department2: "fc-department-select",
  employee1: "fc-employee-select",
  employee2: "fc-employee-select",
  dataselect: "fc-data-select",
  query: "fc-query",
  tableform: "fc-group",
  divider: PRE + "-divider",
  tabs: "fc-tabs",
  elTabPane: PRE + "-tab",
  collapse: "fc-collapse",
  elCollapseItem: PRE + "-collapse-item",
};
