const PRE = "van";
export default {
  button: PRE + "-button",
  icon: PRE + "-icon",
  slider: PRE + "-slider",
  stepper: PRE + "-stepper",
  rate: PRE + "-rate",
  fileUpload: "fc-uploader",
  imageUpload: "fc-uploader",
  cell: PRE + "-cell",
  timePicker: "fc-time-picker",
  timestamp: "fc-date-picker",
  switch: PRE + "-switch",
  select: "fc-select",
  select2: "fc-select",
  cascader: "fc-cascader",
  calendar: "fc-calendar",
  checkbox: "fc-checkbox",
  radio: "fc-radio",
  number: PRE + "-field",
  inputNumber: PRE + "-field",
  input: PRE + "-field",
  textarea: PRE + "-field",
  field: PRE + "-field",
  formItem: PRE + "-field",
  form: PRE + "-form",
  col: PRE + "-col",
  row: PRE + "-row",
  group: "fc-group",
  array: "fc-group",
  object: "fc-sub-form",
  subForm: "fc-sub-form",
};
